#!/usr/local/bin/bash
# 
# Kompile Files
#
# USAGE
if (( $# !=2 ))
then 
  printf "\nUsage: \n";
  printf "ARG1 - Directory to Pull from\n";
  printf "ARG2 - Directory to Dump\n";
  exit 1
fi
#
# ARGUMENTS
target=${1%/}
dump=${2%/}
#
# LOCATIONS
# $target/ = files will be shredded into 1M blocks
# $dump/ = working directory
# $dump/pool/ = final location 
# $dump/limbo/ = temporary location for split
# $dump/keys/ = ordered file pieces
# $dump/output/ = recompiled files
#
# BEGIN
for line in $list
do
    cat "$dump"/pool/"$line" >> "$dump"/output/completed;
    wsha=$( sha256 completed | awk '{ print $NF }' )
    mv "$dump"/output/completed "$dump"/output/"$wsha";
done
